<?php $this->layout('layout::default', ['title' => 'Nasa:n kuvat']) ?>
<div class="app-content">
  <div class="media">
    <img class="mr-3 rounded-circle" src="/images/jermu-bio.png">
    <div class="media-body">

      <h2 class="cover-heading">Learning Rollup</h2>
      <p class="lead h5">Let’s learn how to use <a href="http://rollupjs.org/">Rollup</a>
      </p>

      <!-- JS-generated output will be added here. -->
      <pre class="debug"><code class="debug__output"></code></pre>

      <p class="credits">
        Learn how this was built at 
        <a href="https://code.lengstorf.com/learn-rollup-js/" class="credits__link">code.lengstorf.com
        </a>. Built by <a href="https://github.com/jlengstorf" class="credits__link">@jlengstorf</a>.
      </p>
    </div>
  </div>

</div>