<div class="container d-flex justify-content-between">

      <ul class="list-inline text-xs-center">
        <li class="list-inline-item">
          <a href="https://twitter.com/JukkaAhlgren" target="_blank" data-toggle="tooltip" data-placement="top" title="Ota yhteyttä Twitterissä">
            <i class="fab fa-twitter"></i> @JukkaAhlgren
          </a>
        </li>

        <li class="list-inline-item">
          <a href="https://facebook.com/jukka.ahlgren" target="_blank" data-toggle="tooltip" data-placement="top" title="Ota yhteyttä Facebookissa">
            <i class="fab fa-facebook"></i> Facebook
          </a>
        </li>

        <li class="list-inline-item">
          <a href="https://github.com/jailgreen" target="_blank" data-toggle="tooltip" data-placement="top" title="Seuraa minua GitHubissa">
            <i class="fab fa-github"></i> GitHub
          </a>
        </li>
      </ul>

      <p class="text-xs-center text-md-right">
        &copy; 2017 - <?=date('Y')?> jahlgreen.eu
      </p>
    </div>
